name: only-the-essentials
base: core22
version: '0.6'
summary: The snap that installs most used apps/snaps
description: |
  This snap is for everyone! You can install every app you need! Whenever
  you are a programmer, gamer, or just want to mess with multimedia.
grade: stable
confinement: strict
contact: https://iliantsonev.wordpress.com

parts:
  only-the-essentials:
    plugin: dump
    source: .
    organize:
      only-the-essentials.sh: bin/only-the-essentials

apps:
  only-the-essentials:
    command: bin/only-the-essentials
