name: only-the-essentials
base: core22
version: '1.1-UltraDestructive' 
summary: The snap that installs most used apps/snaps
description: |
  This snap is for everyone! You can install every app you need! Whether
  you are a programmer, gamer, or just want to mess with multimedia.
grade: stable
confinement: classic #let's wish that everything is good
contact: https://iliantsonev.wordpress.com

parts:
  only-the-essentials:
    plugin: dump
    source: .
    override-build: |
      craftctl default
    organize:
      only-the-essentials.sh: bin/only-the-essentials

apps:
  only-the-essentials:
    command: bin/only-the-essentials
